In [1]:
import torch

In [2]:
x = torch.tensor(3.0)
y = torch.tensor(2.0)

x+y, x-y, x/y, x**y

(tensor(5.), tensor(1.), tensor(1.5000), tensor(9.))

In [19]:
x = torch.arange(3, dtype = torch.float32)
x, x[2], len(x), x.shape

#order: the number of axes
#dimensionality: the number of componenets


(tensor([0., 1., 2.]), tensor(2.), 3, torch.Size([3]))

In [12]:
A = torch.arange(6).reshape(3, 2)
A, A.T

(tensor([[0, 1],
         [2, 3],
         [4, 5]]),
 tensor([[0, 2, 4],
         [1, 3, 5]]))

In [14]:
A = torch.arange(6, dtype=torch.float32).reshape(2, 3)
sum_A = A.sum(axis=1, keepdims=True)
A, A / sum_A

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 tensor([[0.0000, 0.3333, 0.6667],
         [0.2500, 0.3333, 0.4167]]))

In [15]:
A.cumsum(axis=0), A.cumsum(axis=1)

(tensor([[0., 1., 2.],
         [3., 5., 7.]]),
 tensor([[ 0.,  1.,  3.],
         [ 3.,  7., 12.]]))

In [20]:
y = torch.ones(3, dtype=torch.float32)
x, y, torch.dot(x, y) == torch.sum(x*y)

(tensor([0., 1., 2.]), tensor([1., 1., 1.]), tensor(True))

In [21]:
A.shape, x.shape, torch.mv(A, x), A@x

(torch.Size([2, 3]), torch.Size([3]), tensor([ 5., 14.]), tensor([ 5., 14.]))

In [22]:
B = torch.ones(3, 4)
torch.mm(A, B), A@B

(tensor([[ 3.,  3.,  3.,  3.],
         [12., 12., 12., 12.]]),
 tensor([[ 3.,  3.,  3.,  3.],
         [12., 12., 12., 12.]]))

In [23]:
u = torch.tensor([3.0, -4.0])
torch.norm(u), torch.abs(u).sum(), torch.norm(torch.ones((4, 9)))

(tensor(5.), tensor(7.), tensor(6.))

In [25]:
X=torch.arange(24).reshape(2, 3, 4)
len(X)
"""
 For a tensor X of arbitrary shape, does len(X) always correspond to the length of a certain axis of X? What is that axis?
---> first axis (axis 0)

"""

2

In [27]:
# X / X.sum(axis=1)
# size가 안 맞ㅇ므

RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 1